spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.209.44.12:10043/dis_admin
    username: dis_admin
    password: dis_admin
    validation-query: SELECT 1
    initial-size: 2
    sql-script-encoding: UTF-8

  jpa:
    database: mysql
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false

  redis:
    host: 10.209.32.38
    port: 10545
    timeout: 60

#logging:
#  config: classpath:prod/logback.xml
#  level:
#    root: INFO


