spring:
  datasource:
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:h2ds
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 10.209.32.38
    port: 10545
    timeout: 60

server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 60
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.damon.oauth.domain

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#logging:
#  config: classpath:/logback.xml
#  level:
#    root: DEBUG
